
module.exports = {
    Login_CONTROLLER: require('./API LIVE/AUTH APIS/LOGIN_CONTROLLER').Login_CONTROLLER,
    Signin_CONTROLLER: require('./API LIVE/AUTH APIS/Signin_CONTROLLER').Signin_CONTROLLER,
    Refresh_CONTROLLER: require('./API LIVE/AUTH APIS/Refresh_CONTROLLER').Refresh_CONTROLLER,
    Verify_CONTROLLER: require('./API LIVE/AUTH APIS/Verify_CONTROLLER').Verify_CONTROLLER,
    Upload_Post_Controller: require('./API LIVE/POST APIS/Upload_Post_CONTROLLER').Upload_Post_Controller,
    Fetch_Post_Controller: require('./API LIVE/POST APIS/Fetch_Post_CONTROLLER').Fetch_Post_Controller,
    Search_Store_CONTROLLER: require('./API LIVE/ACTION APIS/Search_Store_CONTROLLER').Search_Store_Controller,
    Follow_Store_CONTROLLER: require('./API LIVE/ACTION APIS/Follow_Store_CONTROLLER').Follow_Store_Controller,
    Unfollow_Store_CONTROLLER: require('./API LIVE/ACTION APIS/Unfollow_Store_CONTROLLER').Unfollow_Store_Controller,
    Chat_Init_Controller: require('./API LIVE/CHAT APIS/Chat_Init_CONTROLLER').Chat_Init_Controller,
    fetchChatController: require('./API LIVE/CHAT APIS/Fetch_Chat_Message_CONTROLLER').fetchChatController,
    Fetch_Chat_Message_CONTROLLER: require('./API LIVE/CHAT APIS/Fetch_Chat_Message_CONTROLLER').Fetch_Chat_Message_Controller,
    Fetch_ChatID_CONTROLLER: require('./API LIVE/CHAT APIS/Fetch_ChatID_CONTROLLER').Fetch_ChatID_CONTROLLER,
    Save_Message_CONTROLLER: require('./API LIVE/CHAT APIS/Save_Message_CONTROLLER').Save_Message_CONTROLLER,
    Fetch_All_Chats_CONTROLLER: require('./API LIVE/CHAT APIS/Fetch_All_Chats_CONTROLLER').Fetch_All_Chats_CONTROLLER,
    Fetch_Chat_Highlight_Header_CONTROLLER: require('./API LIVE/CHAT APIS/Fetch_Chat_Highlight_Header_CONTROLLER').Fetch_Chat_Highlight_Header_CONTROLLER,
    StoreProductUpload_CONTROLLER: require('../CONTROLLERS/API LIVE/STORE APIS/StoreProductCRUD_CONTROLLER').StoreProductUpload_CONTROLLER,
    StoreProductFetch_CONTROLLER: require('../CONTROLLERS/API LIVE/STORE APIS/StoreProductCRUD_CONTROLLER').StoreProductFetch_CONTROLLER,
    ToggleLikePost_CONTROLLER:require('./API LIVE/POST APIS/ToggleLike_Post_CONTROLLER').ToggleLikePost_Controller,
    CommentPost_CONTROLLER: require('./API LIVE/POST APIS/CommentPost_CONTROLLER').CommentPost_CONTROLLER,
    CommentFetch_CONTROLLER: require('./API LIVE/POST APIS/CommentPost_CONTROLLER').CommentFetch_CONTROLLER,
    ToggleLikeComment_CONTROLLER:require('./API LIVE/POST APIS/ToggleLike_Comment_CONTROLLER').ToggleLikeComment_Controller,
    FetchStockByStoreName_CONTROLLER: require('./API LIVE/ECOMM APIS/FetchStockByStoreName_CONTROLLER').FetchStockByStoreName_CONTROLLER,
    StoreProductDelete_CONTROLLER: require('./API LIVE/STORE APIS/StoreProductCRUD_CONTROLLER').StoreProductDelete_CONTROLLER,
    StoreProductUpdate_CONTROLLER: require('./API LIVE/STORE APIS/StoreProductCRUD_CONTROLLER').StoreProductUpdate_CONTROLLER,
    AddProductToCart_CONTROLLER:require('./API LIVE/STORE APIS/StoreProductCRUD_CONTROLLER').AddProductToCart_CONTROLLER,
    FetchCartProducts_CONTROLLER:require('./API LIVE/STORE APIS/StoreProductCRUD_CONTROLLER').FetchCartProducts_CONTROLLER,
    DeleteCartProducts_CONTROLLER: require('./API LIVE/STORE APIS/StoreProductCRUD_CONTROLLER').DeleteCartProducts_CONTROLLER,
    Payment_CONTROLLER : require('./API LIVE/STRIPE APIS/STRIPE_API_CONTROLLER').PAYMENTSESSION_API__CONTROLLER,
    CreateConnectedAccount_CONTROLLER: require('./API LIVE/STRIPE APIS/STRIPE_API_CONTROLLER').CREATECONNECTEDACCOUNT_API__CONTROLLER,
    UserAccountCheck_CONTROLLER: require('./API LIVE/STRIPE APIS/STRIPE_API_CONTROLLER').USERACCOUNTCHECK_API__CONTROLLER,
    ContinueOnBoardingProcess_CONTROLLER:require('./API LIVE/STRIPE APIS/STRIPE_API_CONTROLLER').CONTINUEONBARDINGPROCESS_API__CONTROLLER,
    FetchFollowersDetail_CONTROLLER:require('./API LIVE/ACTION APIS/FetchFollowersDetail_CONTROLLER').FetchFollowersDetail_CONTROLLER,
    Fetch_Store_ByUserID_CONTROLLER:require('./API LIVE/ACTION APIS/Fetch_Store_ByUserID_CONTROLLER').Fetch_Store_ByUserID_CONTROLLER,
    Deactivate_User_CONTROLLER:require('./API LIVE/ACTION APIS/Deactivate_User_CONTROLLER').Deactivate_User_CONTROLLER,
    Update_User_CONTROLLER:require('./API LIVE/ACTION APIS/Update_User_CONTROLLER').Update_User_CONTROLLER
}